Fix registry handling for rs-core packaging (#1588)
From some local tests, it seems that `cargo` will try to look up dependencies from crates.io unless we package them together (and even then, the registries have to match):

```shell-session
$ cargo --config 'registries.harbor.index="sparse+https://code.futo.org/api/packages/harbor/cargo/"' publish --dry-run -p polycentric-common -p polycentric-core --allow-dirty --no-verify --registry harbor
    Updating `harbor` index
   Packaging polycentric-common v3.3.3 (...)
    Updating crates.io index
    Packaged 38 files, 128.4KiB (32.6KiB compressed)
   Packaging polycentric-core v3.3.3 (...)
    Updating crates.io index
error: failed to prepare local package for uploading

Caused by:
  no matching package named `polycentric-common` found
  location searched: crates.io index
  required by package `polycentric-core v3.3.3 (...)`
```

```shell-session
$ cargo package -p polycentric-common --allow-dirty --no-verify
warning: manifest has no documentation, homepage or repository
  |
  = note: see https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info
   Packaging polycentric-common v3.3.3 (...)
    Updating crates.io index
    Packaged 38 files, 128.4KiB (32.6KiB compressed)

$ cargo package -p polycentric-core --allow-dirty --no-verify
warning: manifest has no documentation, homepage or repository
  |
  = note: see https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info
   Packaging polycentric-core v3.3.3 (...)
    Updating crates.io index
error: failed to prepare local package for uploading

Caused by:
  no matching package named `polycentric-common` found
  location searched: crates.io index
  required by package `polycentric-core v3.3.3 (...)`
```

This PR changes the `package` step to set the `rs-common` dependency of `rs-core` to be from the `harbor` registry and also packages them together.
This should allow `cargo` to resolve the dependency locally without consulting a registry.

I've left the `publish` step using the loop since `rs-common` should be available from the registry by the time `rs-core` is published.

From some local tests, it seems that `cargo` will try to look up dependencies from crates.io unless we package them together (and even then, the registries have to match):

```shell-session
$ cargo --config 'registries.harbor.index="sparse+https://code.futo.org/api/packages/harbor/cargo/"' publish --dry-run -p polycentric-common -p polycentric-core --allow-dirty --no-verify --registry harbor
    Updating `harbor` index
   Packaging polycentric-common v3.3.3 (...)
    Updating crates.io index
    Packaged 38 files, 128.4KiB (32.6KiB compressed)
   Packaging polycentric-core v3.3.3 (...)
    Updating crates.io index
error: failed to prepare local package for uploading

Caused by:
  no matching package named `polycentric-common` found
  location searched: crates.io index
  required by package `polycentric-core v3.3.3 (...)`
```

```shell-session
$ cargo package -p polycentric-common --allow-dirty --no-verify
warning: manifest has no documentation, homepage or repository
  |
  = note: see https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info
   Packaging polycentric-common v3.3.3 (...)
    Updating crates.io index
    Packaged 38 files, 128.4KiB (32.6KiB compressed)

$ cargo package -p polycentric-core --allow-dirty --no-verify
warning: manifest has no documentation, homepage or repository
  |
  = note: see https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info
   Packaging polycentric-core v3.3.3 (...)
    Updating crates.io index
error: failed to prepare local package for uploading

Caused by:
  no matching package named `polycentric-common` found
  location searched: crates.io index
  required by package `polycentric-core v3.3.3 (...)`
```

This PR changes the `package` step to set the `rs-common` dependency of `rs-core` to be from the `harbor` registry and also packages them together.
This should allow `cargo` to resolve the dependency locally without consulting a registry.

I've left the `publish` step using the loop since `rs-common` should be available from the registry by the time `rs-core` is published.

Reviewed-on: https://code.futo.org/harbor/harbor/pulls/1588
Reviewed-by: James Youngblood <james@futo.org>